# Generated by Django 4.2.2 on 2023-06-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_cliente_cedula_alter_cliente_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='code',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
