# Generated by Django 4.2.1 on 2023-07-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_empresa_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'iva',
                'verbose_name_plural': 'iva',
            },
        ),
        migrations.CreateModel(
            name='PagosEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.egreso')),
            ],
            options={
                'verbose_name': 'pagos egreso',
                'verbose_name_plural': 'pagos egreso',
                'order_with_respect_to': 'created',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('otro', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.egreso')),
            ],
            options={
                'verbose_name': 'metodo pago',
                'verbose_name_plural': 'metodos pago',
            },
        ),
    ]
