# Generated by Django 4.2.1 on 2023-07-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egreso',
            name='desglosar',
        ),
    ]
