# Generated by Django 4.2.1 on 2023-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_remove_egreso_desglosar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
